{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.8-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.8-beta.jar",
          "url": "nga-api-1.0.8-beta.jar",
          "size": 327170,
          "sha512": "35cd6b6f2c93f3ee6e5c16acec416045c471c8f3b694399200d36b84282f4b66e0327735541f2f729975c283774c391983a555029dee88bd07d1db17365b995c",
          "sha256": "7bea907c36e49304f4a6c8784efc2f29657cd787e5e9d0ebd1bd323383f0dd2d",
          "sha1": "1d3dacf3bd65506a0ea536b952606b11f2da82cf",
          "md5": "2d311583a079333ff14ca54b322b12f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.8-beta.jar",
          "url": "nga-api-1.0.8-beta.jar",
          "size": 327170,
          "sha512": "35cd6b6f2c93f3ee6e5c16acec416045c471c8f3b694399200d36b84282f4b66e0327735541f2f729975c283774c391983a555029dee88bd07d1db17365b995c",
          "sha256": "7bea907c36e49304f4a6c8784efc2f29657cd787e5e9d0ebd1bd323383f0dd2d",
          "sha1": "1d3dacf3bd65506a0ea536b952606b11f2da82cf",
          "md5": "2d311583a079333ff14ca54b322b12f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.8-beta-javadoc.jar",
          "url": "nga-api-1.0.8-beta-javadoc.jar",
          "size": 261,
          "sha512": "bf581086dff58cb43aa016c79ccba48f9f8e26f000aad842693d3a1cd008d1de2a7cc09ec0f2ae6cf64fe0d11416904a13210215104837edf0fe201d25ac1921",
          "sha256": "9a15f2c626dc2fe08494d2b7aa6f6eae1d2368a0a44a51a1c18a156328ebbeb2",
          "sha1": "121cca95e4aa5aadba716d01cca8f6fb8b03174a",
          "md5": "adfb3b8d53b871f0034c323a91d17bc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.8-beta-sources.jar",
          "url": "nga-api-1.0.8-beta-sources.jar",
          "size": 207218,
          "sha512": "714666c1f92e7a95d6d0d5ade2a5a96289a96b1bade82a7bdcd3a000bd43813d3850ae0586a54a99df1dabfbee266ba6722355ebed26c698359d0f06ccbc0c67",
          "sha256": "76120f34d67842d905b22caad1468fa73ef5b1254e7f673c4cb015532807f02f",
          "sha1": "d25336da22a1d0a9364e2b33af6777882716507b",
          "md5": "dc90eb5482536e50445ea57e1bf40735"
        }
      ]
    }
  ]
}
