{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.27-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.27-beta.jar",
          "url": "nga-api-1.0.27-beta.jar",
          "size": 346018,
          "sha512": "7aaea950059dbd141ba89f42608dee2a74bc728b9346d256105692c0b87b46059ddbaa85360e1cf3465ac1b07038700582ac5cba086dfe54268bb5cea2c20412",
          "sha256": "437947510f01c2a14d1cb68de62413cb6ceff0d2a359e677146170d60a1eb3e2",
          "sha1": "124da0aa71a9d82e648a4797a602bba89ae4f65b",
          "md5": "1646b4a34c0a4347cc7ad3d03b5acbce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.27-beta.jar",
          "url": "nga-api-1.0.27-beta.jar",
          "size": 346018,
          "sha512": "7aaea950059dbd141ba89f42608dee2a74bc728b9346d256105692c0b87b46059ddbaa85360e1cf3465ac1b07038700582ac5cba086dfe54268bb5cea2c20412",
          "sha256": "437947510f01c2a14d1cb68de62413cb6ceff0d2a359e677146170d60a1eb3e2",
          "sha1": "124da0aa71a9d82e648a4797a602bba89ae4f65b",
          "md5": "1646b4a34c0a4347cc7ad3d03b5acbce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.27-beta-javadoc.jar",
          "url": "nga-api-1.0.27-beta-javadoc.jar",
          "size": 261,
          "sha512": "7fff67b9aa61944d9da344f8149c1660302d8a6e0c86100ccc0e75170ca4d60782f2774e49b54a4614a4d99e4a9c3e958d959cc86f6db1a50826493c77fc97d8",
          "sha256": "6e269d0e092e0b71c459580b4cc97ad083f63683ea305aca24ab01855d0e2c39",
          "sha1": "f3e05a61051c3892949a2be5af6b94e6d6ffa4a2",
          "md5": "fb4ffbd6795db4e3528411711228ff94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.27-beta-sources.jar",
          "url": "nga-api-1.0.27-beta-sources.jar",
          "size": 215171,
          "sha512": "a8123af5a6a5e39de77bcc5e990323dcc23d3d7b45fe2d29c6a84f6322a6602dc0c72292bc50ffa5bfaf939ecd85966e4beafe77dedcd372b7300139fd8a9449",
          "sha256": "17f4f8e801d7c2202f64b6ed4b00ee360d6e4d748b63f73f83052dcfe74351c0",
          "sha1": "b88d524293d5a6eac71c0569a406a56144f519b1",
          "md5": "0901908e2c07f6e80477663a4304ab4e"
        }
      ]
    }
  ]
}
