{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.26-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.26-beta.jar",
          "url": "nga-api-1.0.26-beta.jar",
          "size": 346133,
          "sha512": "bc5c9f5d3535cc23bf8119e9fad8db9e35b62acf77a8434147c1a06f889e5f1e3d456084e1b29d59f36a950802a7f7a41da452ed3a84725466c496d99444315b",
          "sha256": "ab7b7be293c626675d79d1721e224e50fb486e46c6b3bb108097617d07da3ce8",
          "sha1": "52e454e2944381f0c46f3644741c511c6a81de02",
          "md5": "329a5b2d54eb76519bd87ead568c0a87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.26-beta.jar",
          "url": "nga-api-1.0.26-beta.jar",
          "size": 346133,
          "sha512": "bc5c9f5d3535cc23bf8119e9fad8db9e35b62acf77a8434147c1a06f889e5f1e3d456084e1b29d59f36a950802a7f7a41da452ed3a84725466c496d99444315b",
          "sha256": "ab7b7be293c626675d79d1721e224e50fb486e46c6b3bb108097617d07da3ce8",
          "sha1": "52e454e2944381f0c46f3644741c511c6a81de02",
          "md5": "329a5b2d54eb76519bd87ead568c0a87"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.26-beta-javadoc.jar",
          "url": "nga-api-1.0.26-beta-javadoc.jar",
          "size": 261,
          "sha512": "cb6827773b0cdf9b87a0a963c0350cbc4659ff5a9a1c657f4421f22872f80fa5e7dd5d0ec12752a29c94c591b832b5f6131e122bc6544a3aa82166e5324d1943",
          "sha256": "7cbd977a77bf6fc68c005ef30e6bf3993f11c1f3f6d163bd805886924ffd4ec1",
          "sha1": "713ebb7d964a2fd015ae0c457b29a1cbb0decab7",
          "md5": "d22f2bd245eb878f8328bb850d46f3c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.26-beta-sources.jar",
          "url": "nga-api-1.0.26-beta-sources.jar",
          "size": 215266,
          "sha512": "49f3bb4a397889855524747bb93e67b9cc432488fe54c2a28930f68dfe16bb76f2c0cd49d27ef21e15af0eed5c06b6d1a56b10490847eb9ce4ccdc9be65bd825",
          "sha256": "fe77af0726972cb8bc390e827ff81686908b8e59ba093b8dfde13cb29461747b",
          "sha1": "2306051ee689a1cfb0a4d437f4e831171438670b",
          "md5": "558c6a38aba0173c4f110bfa5d4ad07c"
        }
      ]
    }
  ]
}
