{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.0.jar",
          "url": "nga-api-1.0.0.jar",
          "size": 323439,
          "sha512": "6e62cd1937430890589de7dc354387aabe4d2afb39ded0f11a13dc19f5ad5cecfe11295f26a45b3396611693a77427ebe327213afb17433dca26fb2b4d8694c2",
          "sha256": "dad96274c3a6be571d710dddde91289ddda059f5fb4c274072b7fcc70e51a352",
          "sha1": "ffc10466ce29485f4f90c3c717e74776504e61fc",
          "md5": "f66efb3b90d45b8d96565483d89abf25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.0.jar",
          "url": "nga-api-1.0.0.jar",
          "size": 323439,
          "sha512": "6e62cd1937430890589de7dc354387aabe4d2afb39ded0f11a13dc19f5ad5cecfe11295f26a45b3396611693a77427ebe327213afb17433dca26fb2b4d8694c2",
          "sha256": "dad96274c3a6be571d710dddde91289ddda059f5fb4c274072b7fcc70e51a352",
          "sha1": "ffc10466ce29485f4f90c3c717e74776504e61fc",
          "md5": "f66efb3b90d45b8d96565483d89abf25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.0-javadoc.jar",
          "url": "nga-api-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ca0a060fcb9c19a83516ba2210cf02b1f19791d804e2c036c13c01c3d989799e27a271b9d36a8dfc495e320df8d18792df0d6dd93e1553162526a77b7cdcf503",
          "sha256": "a297ad62e52fbda2e2f0a9443901967d356c9effc158e6908aa609b8286ab692",
          "sha1": "d8c567733d5159b2007287bfef483d681abe0606",
          "md5": "606c2621c51b349700a315c6493a4343"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.0-sources.jar",
          "url": "nga-api-1.0.0-sources.jar",
          "size": 205287,
          "sha512": "9c5b5c601a8e0e8e8d0bdd76604d1fd4a098233253559f9a08e87060bdf5836f0c6efbb665386c2ca3276a00e1bae3d0282dcd41e73f8d1229587a500b28bb8e",
          "sha256": "4ea6c66546596d572666f145367e4f6b24b333f13bed0d3905ffe5e4103510a0",
          "sha1": "0d23f3ab0c516a9b58eebce65042bac7293becca",
          "md5": "db1da5c546cda533ca7fc90b891d672f"
        }
      ]
    }
  ]
}
