{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.0.jar",
          "url": "nga-api-1.0.0.jar",
          "size": 315787,
          "sha512": "3254ae8f06394f7820d9daa85275a57c57c3309034ffb05fc4bc78b2aca4f17447846a53346f4f48cf1b6394f3cec9dd4616247c47fa94d0293cac1787fca438",
          "sha256": "06301b3217f8a647208dd84f1071b8ad9a2bf61a0d6b8cdee0050daf7c2d98b6",
          "sha1": "e5022c22331e3aaaa5ff47cfd794439aff88ee32",
          "md5": "77fa7332f56dfba7133a1f0e1b436ae3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.0.jar",
          "url": "nga-api-1.0.0.jar",
          "size": 315787,
          "sha512": "3254ae8f06394f7820d9daa85275a57c57c3309034ffb05fc4bc78b2aca4f17447846a53346f4f48cf1b6394f3cec9dd4616247c47fa94d0293cac1787fca438",
          "sha256": "06301b3217f8a647208dd84f1071b8ad9a2bf61a0d6b8cdee0050daf7c2d98b6",
          "sha1": "e5022c22331e3aaaa5ff47cfd794439aff88ee32",
          "md5": "77fa7332f56dfba7133a1f0e1b436ae3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.0-javadoc.jar",
          "url": "nga-api-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "2403af769cee043dacf3e264c6f14e2d84ab83028556d92eae4bb70b2c9bf28b81e679aed84eab68754f9d6c13e1e38c9b3b95892f8198b84a30c272603930dc",
          "sha256": "ad1c9e2dfed08a20cff00e3a194d1fff3f60b1fcedcc132de72a92bc24a63d31",
          "sha1": "284dacb0a3bb56d5f2c511c62424cfe54cb04549",
          "md5": "19ac0b4595a51b19ec040f9e8a382834"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.0-sources.jar",
          "url": "nga-api-1.0.0-sources.jar",
          "size": 201570,
          "sha512": "d2e2f5261091d769f8e185ea322139130f73c6425676cba91cbd362d0942de7718ed2846b2125802d8f2ae04ae6d48ea1af5589b1066bf37bc3527a911ecfe77",
          "sha256": "e19ee3f50b6d1cf516366b5c2b7375bcbee1ed8330cbe48636a1fd2b95618905",
          "sha1": "92cbbf0043e6822a8d4cf4265a53cc68054abf4c",
          "md5": "7304d61e40a59274070d2a1b21dbe70c"
        }
      ]
    }
  ]
}
