{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.0.jar",
          "url": "nga-api-1.0.0.jar",
          "size": 321238,
          "sha512": "f1057fdc8dda86e30f977b555764a4a3db1246e3a90000b927db2e8e50e47123e78f98c460a22ce9f7854804a06d6a81c4061f800f5210a6bfbba5d596b7478a",
          "sha256": "55a6c53f6327b977cedbcd4a6c9e7e97877849b6632e8454421e9d780de23acc",
          "sha1": "27e965ba74ad02281b5b90bb9cd60cbb35e08a98",
          "md5": "1ce70fb2aa4d00e9f6fa9c6de4e6ab63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.0.jar",
          "url": "nga-api-1.0.0.jar",
          "size": 321238,
          "sha512": "f1057fdc8dda86e30f977b555764a4a3db1246e3a90000b927db2e8e50e47123e78f98c460a22ce9f7854804a06d6a81c4061f800f5210a6bfbba5d596b7478a",
          "sha256": "55a6c53f6327b977cedbcd4a6c9e7e97877849b6632e8454421e9d780de23acc",
          "sha1": "27e965ba74ad02281b5b90bb9cd60cbb35e08a98",
          "md5": "1ce70fb2aa4d00e9f6fa9c6de4e6ab63"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.0-javadoc.jar",
          "url": "nga-api-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ca0a060fcb9c19a83516ba2210cf02b1f19791d804e2c036c13c01c3d989799e27a271b9d36a8dfc495e320df8d18792df0d6dd93e1553162526a77b7cdcf503",
          "sha256": "a297ad62e52fbda2e2f0a9443901967d356c9effc158e6908aa609b8286ab692",
          "sha1": "d8c567733d5159b2007287bfef483d681abe0606",
          "md5": "606c2621c51b349700a315c6493a4343"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.0-sources.jar",
          "url": "nga-api-1.0.0-sources.jar",
          "size": 204441,
          "sha512": "d5b030b45f52079dc88e09e0e66a318ba2488231da6c4e234d00865373eeb9866250e3310f22de09d35d1403ce19f06a07c8d462c2add0119050b52d0adc339b",
          "sha256": "7e9429ed52708fee48cb29fcf4b6ac6cb518bfe9d3e707b6ec602f2941b62449",
          "sha1": "f6d06667030220880d770fe486e4ceb43ef72eaa",
          "md5": "b0f5fac4cd54101870e96719d7a69056"
        }
      ]
    }
  ]
}
