{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.3-beta.jar",
          "url": "nga-api-1.0.3-beta.jar",
          "size": 324565,
          "sha512": "1b250315d8a1aa2b2c9dab908858686264aa29cd93a2a680034dc69c62332524de1a8397ef8a16793bfe6bc7447501006c5a9de0f35adc7f1047f492b1843619",
          "sha256": "63e74e4a6c1de5d41ecda4cf06ac29d1e3784022f1e10c5df19ac347b34a99e5",
          "sha1": "9acf0b4a358c7a1e83f75e5c2bddb2310f2acffa",
          "md5": "538d1191a259632410754c6a46d958fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.3-beta.jar",
          "url": "nga-api-1.0.3-beta.jar",
          "size": 324565,
          "sha512": "1b250315d8a1aa2b2c9dab908858686264aa29cd93a2a680034dc69c62332524de1a8397ef8a16793bfe6bc7447501006c5a9de0f35adc7f1047f492b1843619",
          "sha256": "63e74e4a6c1de5d41ecda4cf06ac29d1e3784022f1e10c5df19ac347b34a99e5",
          "sha1": "9acf0b4a358c7a1e83f75e5c2bddb2310f2acffa",
          "md5": "538d1191a259632410754c6a46d958fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.3-beta-javadoc.jar",
          "url": "nga-api-1.0.3-beta-javadoc.jar",
          "size": 261,
          "sha512": "dd923b2b717c5c7a89bd693326f17ed35440bc23cc7fb9508c5803f83cae4925e154b352f46a6cbffbae8b212fc12b714aafc4cdd2d3c91ad20b1f157456e8be",
          "sha256": "cc8a93eca25f653ed9bc6608160a24be1ec83cee0e189eaf2fca8e1a34302ae7",
          "sha1": "f769f028f652616f00e802b4e2dab9146eba967f",
          "md5": "47e17eae542c646ebd1a320226ea060b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.3-beta-sources.jar",
          "url": "nga-api-1.0.3-beta-sources.jar",
          "size": 205839,
          "sha512": "f8163b059ee45d0593521f0f2f523347e66e20990749251a4085dddf7b9b0ef7a7f546dfd0a842dafdc7f8bd7640b6673154f39669b391f8417635d1cdd944c6",
          "sha256": "1db9409673f17f3753f77985b4a2544d7c3ec0a301f36a4009716d71e8b5da30",
          "sha1": "a18adedf4d5ae5c6f2b53af93fb9b093d30cb9b8",
          "md5": "dfec4bdbbab44956d4e8ab20ca32f614"
        }
      ]
    }
  ]
}
