{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.15-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.15-beta.jar",
          "url": "nga-api-1.0.15-beta.jar",
          "size": 333267,
          "sha512": "d837fc1997069ad9c5e969584d11af5847980eea946276fe61a37310b16c56aedd12b245a70a711b826a1237376d293203e1ad7e1d2812109292ad511fa77d47",
          "sha256": "b9a9f902e1ba73febf3abc200c87b653eeebb9838504376528b7a6702e72d516",
          "sha1": "5e49b2d11b146f20c3f04f6653bd0bfc922a83f4",
          "md5": "7312ab8a47d4ee4c2b24bbb8182a262f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.15-beta.jar",
          "url": "nga-api-1.0.15-beta.jar",
          "size": 333267,
          "sha512": "d837fc1997069ad9c5e969584d11af5847980eea946276fe61a37310b16c56aedd12b245a70a711b826a1237376d293203e1ad7e1d2812109292ad511fa77d47",
          "sha256": "b9a9f902e1ba73febf3abc200c87b653eeebb9838504376528b7a6702e72d516",
          "sha1": "5e49b2d11b146f20c3f04f6653bd0bfc922a83f4",
          "md5": "7312ab8a47d4ee4c2b24bbb8182a262f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.15-beta-javadoc.jar",
          "url": "nga-api-1.0.15-beta-javadoc.jar",
          "size": 261,
          "sha512": "28103b115bdecdcaa9d977d4ddb8627a7ccc59766c0733723ae96f37be6490eeecaa992089fb474754ca279e650a9a569e352e0ef6f0a059ca35e4f3da483f4c",
          "sha256": "84b7ac3663e4b6a19a00c3feea039f23b8080d629ecc3652c81641580f6e397c",
          "sha1": "e07caa55acf4230d1f4ec222d8e68874c2c5b4cb",
          "md5": "8cb809c3403370ed7bab3516740f1767"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.15-beta-sources.jar",
          "url": "nga-api-1.0.15-beta-sources.jar",
          "size": 209218,
          "sha512": "de09aaba817fb393f2fb62f8d83717fb10df135920cb29de95366dcbb06f9f98972bb0b6438b80b022e5a1fee7d2511c139f7fe528e208a3e98c742409384eae",
          "sha256": "7851beae4df7ba0aefc2ac6f7d6fb0a5e00df1a78e5bacf3581bb62bd56a32c6",
          "sha1": "e3af5b85c11601a71795c982ceb97a8490379f05",
          "md5": "46c5a247bc9eafd233c56826411c52e5"
        }
      ]
    }
  ]
}
