{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.1-beta.jar",
          "url": "nga-api-1.0.1-beta.jar",
          "size": 324074,
          "sha512": "9e487672b1b0039d79c1fb306c07955c65a3f72b138d168e9d124e46496bfe3077be6143a36b136313a67ddeaa1a2b3c29c8d95889017bbc4255520f7ebc5ea9",
          "sha256": "4eacbc9f37d63af2f62d47a7c2e29261d61c45cd52f6429f4a64dcd602e9429f",
          "sha1": "905c71eeea99f2efeab335cf804f87db25545a22",
          "md5": "7bbb2df249dfc789ba63c10b1282c8d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.1-beta.jar",
          "url": "nga-api-1.0.1-beta.jar",
          "size": 324074,
          "sha512": "9e487672b1b0039d79c1fb306c07955c65a3f72b138d168e9d124e46496bfe3077be6143a36b136313a67ddeaa1a2b3c29c8d95889017bbc4255520f7ebc5ea9",
          "sha256": "4eacbc9f37d63af2f62d47a7c2e29261d61c45cd52f6429f4a64dcd602e9429f",
          "sha1": "905c71eeea99f2efeab335cf804f87db25545a22",
          "md5": "7bbb2df249dfc789ba63c10b1282c8d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.1-beta-javadoc.jar",
          "url": "nga-api-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "350505a0724e64cea1fffeb59695903338ce1d051c51e22b450ef253787fce8ca09d45d21f248de7ad0c6fad0c33cbef642dce6abbb5235b5c8bf3296343dfc4",
          "sha256": "4f09b0cd41b81cc453f5680ff3837c8a24148b427cf6339d172a3eb6cc74c51f",
          "sha1": "142d4a85f8bc3b110ee240a06e323a4fca4057fc",
          "md5": "9498034ddd6678cb55aea2c078520a1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.1-beta-sources.jar",
          "url": "nga-api-1.0.1-beta-sources.jar",
          "size": 205511,
          "sha512": "458c47c0b809c99e18dfdbe4ac1a751b5270520097fad3b9c6f7757905f6cc59eee2a090bc3ef03dc9763ddb4e30623091d461cb70949d156cb2dbec3c77ff92",
          "sha256": "afe8e61aef06a9a4dbbc7744c2e0a2ca91666a314cf01e1efeb0d9ef928820f3",
          "sha1": "a733314ac7038686759981f36c3b8b16d8483097",
          "md5": "a38b19ba090dd9c2a10db801ffc2ebb2"
        }
      ]
    }
  ]
}
