{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.30-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.30-beta.jar",
          "url": "nga-api-1.0.30-beta.jar",
          "size": 347862,
          "sha512": "12bcd375cb900d424074dac924da5cea8344d1f99a67c041cb81c771ed570726799f65ed2fd7ea4adf7741107cfccda09886370c2b028fed29fecda2f524a53c",
          "sha256": "2481983435a3451373d89a2d800ff41e533ec876dc76bcecac3fdc5b10dd4bc0",
          "sha1": "36e3eb995c8d1da86e8c8ea973acf457f848ac7f",
          "md5": "7b1b984eba3e012ac33b3e5253566668"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.30-beta.jar",
          "url": "nga-api-1.0.30-beta.jar",
          "size": 347862,
          "sha512": "12bcd375cb900d424074dac924da5cea8344d1f99a67c041cb81c771ed570726799f65ed2fd7ea4adf7741107cfccda09886370c2b028fed29fecda2f524a53c",
          "sha256": "2481983435a3451373d89a2d800ff41e533ec876dc76bcecac3fdc5b10dd4bc0",
          "sha1": "36e3eb995c8d1da86e8c8ea973acf457f848ac7f",
          "md5": "7b1b984eba3e012ac33b3e5253566668"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.30-beta-javadoc.jar",
          "url": "nga-api-1.0.30-beta-javadoc.jar",
          "size": 261,
          "sha512": "e0c2bd800f51313a2008449ab72b87e7d95196876903882a4c42d268214c3ede94d280d399e64152ae3eaf0f4c13a1da11b28946ca2485de84f1a0ee7f3a2025",
          "sha256": "ae3dd964bdec18fb311815493040de3c36b1a05f0b70adabb05067a18692377f",
          "sha1": "e49972f525fcd461459d03c716ab8ed4f3ff45de",
          "md5": "adb8389181b5473989543d96122a6d8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.30-beta-sources.jar",
          "url": "nga-api-1.0.30-beta-sources.jar",
          "size": 216867,
          "sha512": "5e5e53328b305a3334208984207bc6f0bfbcea4f5e83872b0e67c9f292e7a9cc5ed1af93bad871fd9fb18893b42e83bcb7d049f9b4a1b0fbaf54b43e79204f28",
          "sha256": "49b854cf7c259bf2e768e1fca9de3cfcfd3d11c54bc8b2a3f6388b18709bfda4",
          "sha1": "1c3b8f976de927c975554282f06fec8ef0b6b680",
          "md5": "a9b618f5da9d7b0619ff2f8ee3f2617c"
        }
      ]
    }
  ]
}
