{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.24-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.24-beta.jar",
          "url": "nga-api-1.0.24-beta.jar",
          "size": 345801,
          "sha512": "4ff44165995cb7c2de0225590c64b7c6de62da57573e5e43e0a21ac40d9c45aaf223a83629ed8ca2952db607d726f7c34280aeea0f821db314f131765b8fecb1",
          "sha256": "128942f207989161486756186f26ad4abf73ebcea92db775cfc8e91a26461c4c",
          "sha1": "4fd5aaa8a528c66f8fc7aeb75554f1fa14258ccb",
          "md5": "f1f43b502dd27ed38a628f3c63e70d40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.24-beta.jar",
          "url": "nga-api-1.0.24-beta.jar",
          "size": 345801,
          "sha512": "4ff44165995cb7c2de0225590c64b7c6de62da57573e5e43e0a21ac40d9c45aaf223a83629ed8ca2952db607d726f7c34280aeea0f821db314f131765b8fecb1",
          "sha256": "128942f207989161486756186f26ad4abf73ebcea92db775cfc8e91a26461c4c",
          "sha1": "4fd5aaa8a528c66f8fc7aeb75554f1fa14258ccb",
          "md5": "f1f43b502dd27ed38a628f3c63e70d40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.24-beta-javadoc.jar",
          "url": "nga-api-1.0.24-beta-javadoc.jar",
          "size": 261,
          "sha512": "41c352867a1c299c49240e3813d022447d79838aa8e646dfb958da330100331b259d32db1f841818a0d64faec3487bb3306283ec8568f315cfbf58b2d8c6b8d5",
          "sha256": "98d84bb24387b9b6b7385bab2ee48ce97990af9486bf217de442f277a3679192",
          "sha1": "5a8017d759311475d2f4ddddb4334f2894559512",
          "md5": "467969267024edec36e7c01d3527c06b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.24-beta-sources.jar",
          "url": "nga-api-1.0.24-beta-sources.jar",
          "size": 215146,
          "sha512": "8dedddb0ef3b02f9875a85b39e93875c9d40fa045da400407d2f9f18245511f2eb07c7b1f2a0a073af5f2bd4e64971f0cf7c8e787f73894546a7e384f2f5bf59",
          "sha256": "2f853554959a21a383c5f5c0d205ad279f5bfe8a15d838042586983543bfaa7e",
          "sha1": "5df7a49cedbb9db71285cd232c20bc99836fde73",
          "md5": "a30f840bd177ccd29524bb15858f2d35"
        }
      ]
    }
  ]
}
