{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.24-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.24-beta.jar",
          "url": "nga-api-1.0.24-beta.jar",
          "size": 346101,
          "sha512": "5182381783c2b23a7119f1e8039899dfb5f0b009cfe1f449f5dc076787eb71c916b8716df5a6fa19ecaa0ad48b2b92d3cae156d049707c15a666adb3018ed2a9",
          "sha256": "572208f5038c671a8ace15cf6d76026ee24e3152e01057789da5aba309076df4",
          "sha1": "bedf3a201d9d5a185b88715f3042e7245678d42a",
          "md5": "16483b1b2935521cf7bfb71fb0e2c6bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.24-beta.jar",
          "url": "nga-api-1.0.24-beta.jar",
          "size": 346101,
          "sha512": "5182381783c2b23a7119f1e8039899dfb5f0b009cfe1f449f5dc076787eb71c916b8716df5a6fa19ecaa0ad48b2b92d3cae156d049707c15a666adb3018ed2a9",
          "sha256": "572208f5038c671a8ace15cf6d76026ee24e3152e01057789da5aba309076df4",
          "sha1": "bedf3a201d9d5a185b88715f3042e7245678d42a",
          "md5": "16483b1b2935521cf7bfb71fb0e2c6bc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.24-beta-javadoc.jar",
          "url": "nga-api-1.0.24-beta-javadoc.jar",
          "size": 261,
          "sha512": "41c352867a1c299c49240e3813d022447d79838aa8e646dfb958da330100331b259d32db1f841818a0d64faec3487bb3306283ec8568f315cfbf58b2d8c6b8d5",
          "sha256": "98d84bb24387b9b6b7385bab2ee48ce97990af9486bf217de442f277a3679192",
          "sha1": "5a8017d759311475d2f4ddddb4334f2894559512",
          "md5": "467969267024edec36e7c01d3527c06b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.24-beta-sources.jar",
          "url": "nga-api-1.0.24-beta-sources.jar",
          "size": 215165,
          "sha512": "cd1b74bea6cecbadfe40c121b57d615f8b56390d9c78ab5d0370f9ffb2153381bb0681be0a88234953d2d0401b0ebbe72306799892953c9bdb72789329742d25",
          "sha256": "debda94cd3a8ac771b07b79d581864ddd46ceee90ea116e36e7c2ba2fcf08cee",
          "sha1": "2f29b0c836c31eff4da45a39f82d015846155632",
          "md5": "7dda09104cf2097433c89f1a41c2c995"
        }
      ]
    }
  ]
}
