{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.7-beta.jar",
          "url": "nga-api-1.0.7-beta.jar",
          "size": 326585,
          "sha512": "1102e9969d56b6c5c1daa26919c57a1e885dbee47786493da7f92d5eb93471e6de471a314c0048c4f068d8d37a7577a4ce7e49f6d9d93eb3b3c395687628a810",
          "sha256": "c0966813116d9674b3cecf838e5ecfb8085697540cc5f04c59498a8594d95e3d",
          "sha1": "7e2f242c4265ca917327736cbd0cd7d9221a361a",
          "md5": "3cd37e1534b1f9c22af8edc77385bec5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.7-beta.jar",
          "url": "nga-api-1.0.7-beta.jar",
          "size": 326585,
          "sha512": "1102e9969d56b6c5c1daa26919c57a1e885dbee47786493da7f92d5eb93471e6de471a314c0048c4f068d8d37a7577a4ce7e49f6d9d93eb3b3c395687628a810",
          "sha256": "c0966813116d9674b3cecf838e5ecfb8085697540cc5f04c59498a8594d95e3d",
          "sha1": "7e2f242c4265ca917327736cbd0cd7d9221a361a",
          "md5": "3cd37e1534b1f9c22af8edc77385bec5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.7-beta-javadoc.jar",
          "url": "nga-api-1.0.7-beta-javadoc.jar",
          "size": 261,
          "sha512": "563f9060c9b8b75bd5614d2bc72aff02cd0c0862b2bdded28a74918001f5dd81a383352e84940a5fb4f666abb49f28b93971d79da9b2296edffefc2d19ad0772",
          "sha256": "42335712165fe1d2b29525e2087de842de0cf3d8a3af86689c72a704b328b731",
          "sha1": "b53432f6cd3ef2e2f2419b53fb4dbaa6550e489c",
          "md5": "026173eea16b996e89422801e32c23b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.7-beta-sources.jar",
          "url": "nga-api-1.0.7-beta-sources.jar",
          "size": 206964,
          "sha512": "596242b1e4eacc2d3aa94baef1ab22e0860a0bb1a8f6e9685eb7484481721f7273c227221fdc741d3aa72665f2b5c96cc24acbb5c72fec943a0751ce657d9a71",
          "sha256": "f93c43b36208321873202372d62a1c3f9a416ba99c2827f1c73afb1f0897c093",
          "sha1": "139a017db1225db870191029da3c2841c8577c8e",
          "md5": "7722e90132e029948bb877d294a5e043"
        }
      ]
    }
  ]
}
