{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.7-beta.jar",
          "url": "nga-api-1.0.7-beta.jar",
          "size": 326637,
          "sha512": "665e51d114139412033e401c04bd23f56e0d34a4451523bd5b936ffd4c375b92594d82e6d0f2c18394eb23567a65240f4f6eca477a23fa20b80dc6c7921cdaf4",
          "sha256": "e5b518f48bb0d7a5cabd45a1bd24ad003d9ea28b641d099799e6dcc0a790300a",
          "sha1": "b6e83e4bc7ededc508cc7f0582c5430e9d7bf2d0",
          "md5": "bd63a22879ee4280f40318d735805d01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.7-beta.jar",
          "url": "nga-api-1.0.7-beta.jar",
          "size": 326637,
          "sha512": "665e51d114139412033e401c04bd23f56e0d34a4451523bd5b936ffd4c375b92594d82e6d0f2c18394eb23567a65240f4f6eca477a23fa20b80dc6c7921cdaf4",
          "sha256": "e5b518f48bb0d7a5cabd45a1bd24ad003d9ea28b641d099799e6dcc0a790300a",
          "sha1": "b6e83e4bc7ededc508cc7f0582c5430e9d7bf2d0",
          "md5": "bd63a22879ee4280f40318d735805d01"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.7-beta-javadoc.jar",
          "url": "nga-api-1.0.7-beta-javadoc.jar",
          "size": 261,
          "sha512": "563f9060c9b8b75bd5614d2bc72aff02cd0c0862b2bdded28a74918001f5dd81a383352e84940a5fb4f666abb49f28b93971d79da9b2296edffefc2d19ad0772",
          "sha256": "42335712165fe1d2b29525e2087de842de0cf3d8a3af86689c72a704b328b731",
          "sha1": "b53432f6cd3ef2e2f2419b53fb4dbaa6550e489c",
          "md5": "026173eea16b996e89422801e32c23b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.7-beta-sources.jar",
          "url": "nga-api-1.0.7-beta-sources.jar",
          "size": 206982,
          "sha512": "4f53801b1a55c0e100efa124f065b8009eae40d979257b4703b2cde4b77094acb0ec86fd8dcc2e0e3206951408b9cedea2f5db0a84329a5cae04037d179fec75",
          "sha256": "ccd8a51fed17e4de3e50bddc7b411f07af8882c2a227b2624672f98715e768ea",
          "sha1": "e4426699a51f8073f320395d91462a9e15cb5297",
          "md5": "1f8ee39314c52a42b2d7e2f23ecca093"
        }
      ]
    }
  ]
}
