{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.7-beta.jar",
          "url": "nga-api-1.0.7-beta.jar",
          "size": 326685,
          "sha512": "1f77f3cda576064265e5d0999d31c924122891c54472b7209e217a7ffc50bbb152c9ca3e0e8f0b3fb3d078f434c5573cbd835447c6fab751febcb23bc6f3f84e",
          "sha256": "7f808c379c392aaa529669357c27ac214b34747284d52fbfecddda94afe90531",
          "sha1": "fca1eb37b0022d4fdc76320b46bee4f298e943e6",
          "md5": "a07d0a27873139d35318558c11ce95fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.7-beta.jar",
          "url": "nga-api-1.0.7-beta.jar",
          "size": 326685,
          "sha512": "1f77f3cda576064265e5d0999d31c924122891c54472b7209e217a7ffc50bbb152c9ca3e0e8f0b3fb3d078f434c5573cbd835447c6fab751febcb23bc6f3f84e",
          "sha256": "7f808c379c392aaa529669357c27ac214b34747284d52fbfecddda94afe90531",
          "sha1": "fca1eb37b0022d4fdc76320b46bee4f298e943e6",
          "md5": "a07d0a27873139d35318558c11ce95fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.7-beta-javadoc.jar",
          "url": "nga-api-1.0.7-beta-javadoc.jar",
          "size": 261,
          "sha512": "563f9060c9b8b75bd5614d2bc72aff02cd0c0862b2bdded28a74918001f5dd81a383352e84940a5fb4f666abb49f28b93971d79da9b2296edffefc2d19ad0772",
          "sha256": "42335712165fe1d2b29525e2087de842de0cf3d8a3af86689c72a704b328b731",
          "sha1": "b53432f6cd3ef2e2f2419b53fb4dbaa6550e489c",
          "md5": "026173eea16b996e89422801e32c23b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.7-beta-sources.jar",
          "url": "nga-api-1.0.7-beta-sources.jar",
          "size": 206999,
          "sha512": "c05004c66acbe67358e837bcdb9720465198b910509e1662bd6cfe86057e806e326ada7bbe96ff7f2bbaf361228c324e75ac308602685468ff8c587e3e261355",
          "sha256": "5cd8a0b0f663d0c26f28f43f20223345b9d6a209023937bf5dcf82d976976e4a",
          "sha1": "5f112e74e47657f5c38a777182e73fa52322f85d",
          "md5": "e4a03c5a05b5b015df262c62878343f6"
        }
      ]
    }
  ]
}
