{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.29-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.29-beta.jar",
          "url": "nga-api-1.0.29-beta.jar",
          "size": 347461,
          "sha512": "65570d09a56220481981660f4255061250f33b6ee99f6e1eddece2ac3d308b256dbc18440c46dcb89847d9742d7725d2f4d626f03b921213a0802938fcbf589a",
          "sha256": "da2574f0b56e34a998c11bccfa9c38bc82b370e50911840348f2d019ef4bb460",
          "sha1": "9c94b9e4f43fbc65949145e78e41a44d5bf0bc1b",
          "md5": "24fc61deaf9ddac1bfc63e54106b0fa6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.29-beta.jar",
          "url": "nga-api-1.0.29-beta.jar",
          "size": 347461,
          "sha512": "65570d09a56220481981660f4255061250f33b6ee99f6e1eddece2ac3d308b256dbc18440c46dcb89847d9742d7725d2f4d626f03b921213a0802938fcbf589a",
          "sha256": "da2574f0b56e34a998c11bccfa9c38bc82b370e50911840348f2d019ef4bb460",
          "sha1": "9c94b9e4f43fbc65949145e78e41a44d5bf0bc1b",
          "md5": "24fc61deaf9ddac1bfc63e54106b0fa6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.29-beta-javadoc.jar",
          "url": "nga-api-1.0.29-beta-javadoc.jar",
          "size": 261,
          "sha512": "9a57ead3defbbbf9c502cf3e4ac06f11ce94f0449f2dfac24eaae1b3e1b2b22a689057a21de65acc953fd77a30f247ef83afee697e65e37f342bf5b78bee617d",
          "sha256": "eb60e906e5dc691d5a03a25b30fbb63d68650fe3c900f70810fe212a97500dde",
          "sha1": "465d3455ff94e9fd196ba5625e3496f9ca3a465d",
          "md5": "ee5dc66b325709d4e478588e4ecf0d6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.29-beta-sources.jar",
          "url": "nga-api-1.0.29-beta-sources.jar",
          "size": 216665,
          "sha512": "d3e47a8ea2c99e89b8250e4d8a10b1b3a130c2561c8f1e58ccbb962cc35fc65e91803c25f51760de578510aa039f53d8b368a165d4c7d301fdc3c5b555e7b4cb",
          "sha256": "17828fb0b79f0b5aa5e91a797c77aa0ee2cb40b54c4be7f34942e467031b30db",
          "sha1": "58cc1dabaf5a529a3ff75587e0d82a34197361f8",
          "md5": "bc4209d9c240a1b2b7020f79a4a52d0d"
        }
      ]
    }
  ]
}
