{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.14-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.14-beta.jar",
          "url": "nga-api-1.0.14-beta.jar",
          "size": 333231,
          "sha512": "2e701515c039ab0c66f3fe826464027f1a97db2aa2894b797295d407d53ff7db6a35ae60e1a1c2803518e327ca32f9b24187d3ed25a6022804797e1e7251b964",
          "sha256": "6c9026d417f0989a083781d22b2d2d5da6f8935c775875c99b2c1b949255d644",
          "sha1": "daf956ffa80b13f20af27ffadacfb3b50504ff06",
          "md5": "0eb855a90f875916345d1effa7bc178e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.14-beta.jar",
          "url": "nga-api-1.0.14-beta.jar",
          "size": 333231,
          "sha512": "2e701515c039ab0c66f3fe826464027f1a97db2aa2894b797295d407d53ff7db6a35ae60e1a1c2803518e327ca32f9b24187d3ed25a6022804797e1e7251b964",
          "sha256": "6c9026d417f0989a083781d22b2d2d5da6f8935c775875c99b2c1b949255d644",
          "sha1": "daf956ffa80b13f20af27ffadacfb3b50504ff06",
          "md5": "0eb855a90f875916345d1effa7bc178e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.14-beta-javadoc.jar",
          "url": "nga-api-1.0.14-beta-javadoc.jar",
          "size": 261,
          "sha512": "fb02c8c4a9d171d7d7ee02e9476882fce19d91bdc123e56ba9aaf061bfbaaf815478046242aa00e1f0793f49d9219137e620210f754de7e1d84e4f475059b3d5",
          "sha256": "6858299ba5605ec14a96af87e9b25dc8e6bfa3f3281a7b5beae5ca131dc8180b",
          "sha1": "992aed98d2a294ed2aa94edf050323e6f386e7ff",
          "md5": "91a42c63680830be61224435c30be8a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.14-beta-sources.jar",
          "url": "nga-api-1.0.14-beta-sources.jar",
          "size": 209173,
          "sha512": "763cad05a7ce47eb906ddf2c551cc6d51531dafd177c1ec6624bf4b8024163a5bf4b6674640fa2e4c9eaab19c2618c6f684eed9ecde74434e088ca42cbbe7d8f",
          "sha256": "29552cb8ab4ddb24263a03dec2342cf36592e74e816e3f0a33a262ee8302c44a",
          "sha1": "acd7ea6a52d12f1405bbaea22d3d04db30d930ca",
          "md5": "7e2e294ea57affd4370e053f51a598b9"
        }
      ]
    }
  ]
}
