{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.nga",
    "module": "nga-api",
    "version": "1.0.14-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.14-beta.jar",
          "url": "nga-api-1.0.14-beta.jar",
          "size": 333265,
          "sha512": "dcbe1839b2cb19fdc2d533c47fb0abc81f90c10e19058411ff563cea9af5566345310ba11f11b2dd66c7abb15e865b25fdd7207f01cc7bc7971d8dfa83bf8f1f",
          "sha256": "c1c962bafc3a213436503e34628336399820fee967d264b01cee104e1d28c3bf",
          "sha1": "034309e2822253e1241e09f4d4211a581c31e3b1",
          "md5": "31280469eaad01c8ba328cade1940214"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.4"
          }
        }
      ],
      "files": [
        {
          "name": "nga-api-1.0.14-beta.jar",
          "url": "nga-api-1.0.14-beta.jar",
          "size": 333265,
          "sha512": "dcbe1839b2cb19fdc2d533c47fb0abc81f90c10e19058411ff563cea9af5566345310ba11f11b2dd66c7abb15e865b25fdd7207f01cc7bc7971d8dfa83bf8f1f",
          "sha256": "c1c962bafc3a213436503e34628336399820fee967d264b01cee104e1d28c3bf",
          "sha1": "034309e2822253e1241e09f4d4211a581c31e3b1",
          "md5": "31280469eaad01c8ba328cade1940214"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.14-beta-javadoc.jar",
          "url": "nga-api-1.0.14-beta-javadoc.jar",
          "size": 261,
          "sha512": "73d453129d353c329fd4cc3c7d47af07f72882fc0281f02413a7cb4b5cfe95e5d4ad31f736a7a60cd3eb9cbe30ced54ac628be4fcd2b5ac3e00217d4a100474f",
          "sha256": "f13c9eb036047ad7ea46bfa9bc268707121805f46856b781f13188317b9cd0b6",
          "sha1": "17c185a453419b0c6a194aee3dc2e54cedec7f9d",
          "md5": "582efb68ab0e0e979c35150ffcc9c331"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nga-api-1.0.14-beta-sources.jar",
          "url": "nga-api-1.0.14-beta-sources.jar",
          "size": 209222,
          "sha512": "83ba4c0282df598c0510754349531fb04775fa021da29e45cb350f8fbd268a4a5f7e577c494e8069dd9c0569defc8b39af1edfd82b9709d75d31eb95fc3398a7",
          "sha256": "0367404cd346e9a2c3dbab5f6039998e39b885295404699c0fa1e9476f412ec5",
          "sha1": "eb5f11e40b94c59977e660030bd8da1cea8b5d0f",
          "md5": "4568a501da4bc0a98908c1cbde30cd28"
        }
      ]
    }
  ]
}
